marker = '<?xml version="1.0" encoding="UTF-8"?>\n'

replacer = ('<!DOCTYPE PATDOC SYSTEM \"ST32-US-Grant-025xml.dtd\" ['
          '<!ENTITY frac12 \' \'>'
          '<!ENTITY mdash \'-\'>'
          '<!ENTITY num \' \'>'
          '<!ENTITY uuml \'u\'>'
          '<!ENTITY ldquo \' \'>'
          '<!ENTITY rdquo \' \'>'
          '<!ENTITY ouml \'o \'>'
          '<!ENTITY angst \' \'>'
          '<!ENTITY copy \'(c)\'>'
          '<!ENTITY auml \'a\'>'
          '<!ENTITY trade \'(tm)\'>'
          '<!ENTITY deg \'(deg)\'>'
          '<!ENTITY reg \'(R)\'>'
          '<!ENTITY quest \'?\'>'
          '<!ENTITY times \' \'>'
          '<!ENTITY acirc \'a\'>'
          '<!ENTITY prime \"\'\">'
          '<!ENTITY Prime \'\"\'>'
          '<!ENTITY frac14 \' \'>'
          '<!ENTITY lsquo \"\'\">'
          '<!ENTITY rsquo \'\"\'>'
          '<!ENTITY rsqb \' \'>'
          '<!ENTITY lsqb \' \'>'
          '<!ENTITY pgr \' \'>'
          '<!ENTITY emsp \' \'>'
          '<!ENTITY thgr \' \'>'
          '<!ENTITY rsqb \' \'>'
          '<!ENTITY minus \'-\'>'
          '<!ENTITY plus \'+\'>'
          '<!ENTITY lE \'>\'>'
          '<!ENTITY lt \'<\'>'
          '<!ENTITY gE \'>\'>'
          '<!ENTITY gt \'<\'>'
          '<!ENTITY sect \' \'>'
          '<!ENTITY agr \' \'>'
          '<!ENTITY equals \'=\'>'
          '<!ENTITY oslash \'o\'>'
          '<!ENTITY middot \'-\'>'
          '<!ENTITY eacute \'e\'>'
          '<!ENTITY tilde \'~\'>'
          '<!ENTITY commat \' \'>'
          '<!ENTITY aring \' \'>'
          '<!ENTITY yen \' \'>'
          '<!ENTITY Union \' \'>'
          '<!ENTITY boxdr \' \'>'
          '<!ENTITY lgr \' \'>'
          '<!ENTITY Rhalfcircle \' \'>'
          '<!ENTITY nbsp \' \'>'
          '<!ENTITY sime \' \'>'
          '<!ENTITY frac78 \' \'>'
          '<!ENTITY psgr \' \'>'
          '<!ENTITY equiv \' \'>'
          '<!ENTITY rgr \' \'>'
          '<!ENTITY boxur \' \'>'
          '<!ENTITY LeftBracketingBar \' \'>'
          '<!ENTITY Congruent \' \'>'
          '<!ENTITY utrif \' \'>'
          '<!ENTITY ngr \' \'>'
          '<!ENTITY TildeTilde \' \'>'
          '<!ENTITY THgr \' \'>'
          '<!ENTITY darr \' \'>'
          '<!ENTITY cacute \' \'>'
          '<!ENTITY mgr \' \'>'
          '<!ENTITY OHgr \' \'>'
          '<!ENTITY square \' \'>'
          '<!ENTITY Auml \'A\'>'
          '<!ENTITY Sum \'S\'>'
          '<!ENTITY brvbar \' \'>'
          '<!ENTITY agrave \' \'>'
          '<!ENTITY Ocirc \'O\'>'
          '<!ENTITY verbar \' \'>'
          '<!ENTITY Pi \'Pi\'>'
          '<!ENTITY xgr \' \'>'
          '<!ENTITY frac15 \' \'>'
          '<!ENTITY larr \' \'>'
          '<!ENTITY egrave \' \'>'
          '<!ENTITY aelig \' \'>'
          '<!ENTITY sub \'(=\'>'
          '<!ENTITY lcub \' \'>'
          '<!ENTITY frac18 \' \'>'
          '<!ENTITY prop \' \'>'
          '<!ENTITY Uuml \' \'>'
          '<!ENTITY ntilde \'~\'>'
          '<!ENTITY ocirc \' \'>'
          '<!ENTITY theta \'t\'>'
          '<!ENTITY RightArrow \'->\'>'
          '<!ENTITY Oslash \'O\'>'
          '<!ENTITY vellip \' \'>'
          '<!ENTITY squf \' \'>'
          '<!ENTITY ggr \' \'>'
          '<!ENTITY yuml \' \'>'
          '<!ENTITY infin \' \'>'
          '<!ENTITY frac16 \' \'>'
          '<!ENTITY thinsp \' \'>'
          '<!ENTITY Proportional \' \'>'
          '<!ENTITY ecirc \' \'>'
          '<!ENTITY PHgr \' \'>'
          '<!ENTITY Scirc \' \'>'
          '<!ENTITY boxH \' \'>'
          '<!ENTITY GreaterEqual \'>=\'>'
          '<!ENTITY frac23 \' \'>'
          '<!ENTITY frac25 \' \'>'
          '<!ENTITY nabla \' \'>'
          '<!ENTITY ohgr \' \'>'
          '<!ENTITY bgr \' \'>'
          '<!ENTITY rarr \' \'>'
          '<!ENTITY gamma \' \'>'
          '<!ENTITY tgr \' \'>'
          '<!ENTITY divide \'/\'>'
          '<!ENTITY Ouml \' \'>'
          '<!ENTITY sgr \' \'>'
          '<!ENTITY igrave \' \'>'
          '<!ENTITY bsol \' \'>'
          '<!ENTITY plusmn \'+-\'>'
          '<!ENTITY CenterDot \'-\'>'
          '<!ENTITY frac38 \' \'>'
          '<!ENTITY frac34 \' \'>'
          '<!ENTITY perp \' \'>'
          '<!ENTITY dtrif \' \'>'
          '<!ENTITY Delta \'D\'>'
          '<!ENTITY there4 \' \'>'
          '<!ENTITY pi \'Pi\'>'
          '<!ENTITY euml \'e\'>'
          '<!ENTITY kgr \' \'>'
          '<!ENTITY iacute \' \'>'
          '<!ENTITY part \' \'>'
          '<!ENTITY bull \' \'>'
          '<!ENTITY xcirc \' \'>'
          '<!ENTITY excl \' \'>'
          '<!ENTITY phgr \' \'>'
          '<!ENTITY ocir \' \'>'
          '<!ENTITY ensp \' \'>'
          '<!ENTITY ccedil \' \'>'
          '<!ENTITY par \' \'>'
          '<!ENTITY boxvl \' \'>'
          '<!ENTITY isin \' \'>'
          '<!ENTITY compfn \' \'>'
          '<!ENTITY af \' \'>'
          '<!ENTITY RightVector \' \'>'
          '<!ENTITY it \' \'>'
          '<!ENTITY ap \' \'>'
          '<!ENTITY uarr \' \'>'
          '<!ENTITY oplus \'O\'>'
          '<!ENTITY PSgr \' \'>'
          '<!ENTITY frac58 \' \'>'
          '<!ENTITY khgr \' \'>'
          '<!ENTITY diam \'O\'>'
          '<!ENTITY zgr \' \'>'
          '<!ENTITY ne \' \'>'
          '<!ENTITY Dgr \' \'>'
          '<!ENTITY eta \' \'>'
          '<!ENTITY nldr \' \'>'
          '<!ENTITY uacute \' \'>'
          '<!ENTITY diams \' \'>'
          '<!ENTITY Parenopenst \' \'>'
          '<!ENTITY aacute \' \'>'
          '<!ENTITY Element \' \'>'
          '<!ENTITY dgr \' \'>'
          '<!ENTITY fnof \' \'>'
          '<!ENTITY eegr \' \'>'
          '<!ENTITY Gamma \' \'>'
          '<!ENTITY frac13 \' \'>'
          '<!ENTITY egr \' \'>'
          '<!ENTITY Sgr \' \'>'
          '<!ENTITY sigma \' \'>'
          '<!ENTITY oacute \'O\'>'
          '<!ENTITY tau \' \'>'
          '<!ENTITY int \' \'>'
          '<!ENTITY xi \' \'>'
          '<!ENTITY dagger \' \'>'
          '<!ENTITY DoubleVerticalBar \' \'>'
          '<!ENTITY Parenclosest \' \'>'
          '<!ENTITY NotEqual \' \'>'
          '<!ENTITY ograve \' \'>'
          '<!ENTITY ucirc \' \'>'
          '<!ENTITY RightBracketingBar \' \'>'
          '<!ENTITY hellip \' \'>'
          '<!ENTITY Circlesolid \' \'>'
          '<!ENTITY mnplus \' \'>'
          '<!ENTITY CirclePlus \' \'>'
          '<!ENTITY varnothing \' \'>'
          '<!ENTITY AutoRightMatch \' \'>'
          '<!ENTITY ctdot \' \'>'
          '<!ENTITY cong \' \'>'
          '<!ENTITY rcub \' \'>'
          '<!ENTITY ugr \' \'>'
          '<!ENTITY Acirc \' \'>'
          '<!ENTITY utdot \' \'>'
          '<!ENTITY Ovalsolid \' \'>'
          '<!ENTITY Phi \' \'>'
          '<!ENTITY Psi \' \'>'
          '<!ENTITY angle \' \'>'
          '<!ENTITY PartialD \' \'>'
          '<!ENTITY Asteriskpseud \' \'>'
          '<!ENTITY Ggr \' \'>'
          '<!ENTITY chi \' \'>'
          '<!ENTITY frac35 \' \'>'
          '<!ENTITY otilde \' \'>'
          '<!ENTITY varphi \' \'>'
          '<!ENTITY LeftAngleBracket \' \'>'
          '<!ENTITY ee \' \'>'
          '<!ENTITY Lgr \' \'>'
          '<!ENTITY TildeFullEqual \' \'>'
          '<!ENTITY AutoLeftMatch \' \'>'
          '<!ENTITY Omega \' \'>'
          '<!ENTITY boxul \' \'>'
          '<!ENTITY DoubleDot \' \'>'
          '<!ENTITY phi \' \'>'
          '<!ENTITY NewLine \' \'>'
          '<!ENTITY star \' \'>'
          '<!ENTITY ycirc \' \'>'
          '<!ENTITY para \' \'>'
          '<!ENTITY Egr \' \'>'
          '<!ENTITY dd \' \'>'
          '<!ENTITY ominus \' \'>'
          '<!ENTITY ccirc \' \'>'
          '<!ENTITY leq \' \'>'
          '<!ENTITY beta \' \'>'
          '<!ENTITY starf \' \'>'
          '<!ENTITY boxdl \' \'>'
          '<!ENTITY rho \' \'>'
          '<!ENTITY delta \' \'>'
          '<!ENTITY alpha \' \'>'
          '<!ENTITY omega \' \'>'
          '<!ENTITY igr \' \'>'
          '<!ENTITY varepsilon \' \'>'
          '<!ENTITY Rectversolid \' \'>'
          '<!ENTITY Dagger \' \'>'
          '<!ENTITY cup \' \'>'
          '<!ENTITY Integral \' \'>'
          '<!ENTITY frac45 \' \'>'
          '<!ENTITY mu \' \'>'
          '<!ENTITY micro \' \'>'
          '<!ENTITY Ugrave \' \'>'
          '<!ENTITY GreaterFullEqual \' \'>'
          '<!ENTITY forall \' \'>'
          '<!ENTITY iuml \' \'>'
          '<!ENTITY lambda \' \'>'
          '<!ENTITY PlusMinus \' \'>'
          '<!ENTITY Ccirc \' \'>'
          '<!ENTITY UpTee \' \'>'
          '<!ENTITY OpenCurlyDoubleQuote \' \'>'
          '<!ENTITY LowerLeftArrow \' \'>'
          '<!ENTITY ii \' \'>'
          '<!ENTITY Ntilde \' \'>'
          '<!ENTITY ang \' \'>'
          '<!ENTITY exist \' \'>'
          '<!ENTITY Product \' \'>'
          '<!ENTITY Star \' \'>'
          '<!ENTITY LessFullEqual \' \'>'
          '<!ENTITY rlarr \' \'>'
          '<!ENTITY utilde \' \'>'
          '<!ENTITY Icirc \' \'>'
          '<!ENTITY nu \' \'>'
          '<!ENTITY LeftFloor \' \'>'
          '<!ENTITY psi \' \'>'
          '<!ENTITY Implies \' \'>'
          '<!ENTITY LeftDoubleBracketingBar \' \'>'
          '<!ENTITY UnderBrace \' \'>'
          '<!ENTITY RightAngleBracket \' \'>'
          '<!ENTITY hslash \' \'>'
          '<!ENTITY nequiv \' \'>'
          '<!ENTITY scirc \' \'>'
          '<!ENTITY TildeEqual \' \'>'
          '<!ENTITY upsilon \' \'>'
          '<!ENTITY Sigma \' \'>'
          '<!ENTITY Lambda \' \'>'
          '<!ENTITY And \' \'>'
          '<!ENTITY kappa \' \'>'
          '<!ENTITY DoubleRightArrow \' \'>'
          '<!ENTITY cap \' \'>'
          '<!ENTITY VerticalSeparator \' \'>'
          '<!ENTITY Del \' \'>'
          '<!ENTITY div \' \'>'
          '<!ENTITY CloseCurlyDoubleQuote \' \'>'
          '<!ENTITY Intersection \' \'>'
          '<!ENTITY UpperLeftArrow \' \'>'
          '<!ENTITY Exists \' \'>'
          '<!ENTITY Wedge \' \'>'
          '<!ENTITY Hcirc \' \'>'
          '<!ENTITY Ucirc \' \'>'
          '<!ENTITY notin \' \'>'
          '<!ENTITY atilde \' \'>'
          '<!ENTITY bigtriangledown \' \'>'
          '<!ENTITY RightFloor \' \'>'
          '<!ENTITY varpi \' \'>'
          '<!ENTITY MinusPlus \' \'>'
          '<!ENTITY epsi \' \'>'
          '<!ENTITY Ecirc \' \'>'
          '<!ENTITY RightDoubleBracketingBar \' \'>'
          '<!ENTITY Theta \' \'>'
          '<!ENTITY ic \' \'>'
          '<!ENTITY wcirc \' \'>'
          '<!ENTITY LessLess \' \'>'
          '<!ENTITY sup \' \'>'
          '<!ENTITY PrecedesEqual \' \'>'
          '<!ENTITY DoubleLeftRightArrow \' \'>'
          '<!ENTITY ForAll \' \'>'
          '<!ENTITY hcirc \' \'>'
          '<!ENTITY Equal \' \'>'
          '<!ENTITY LeftCeiling \' \'>'
          '<!ENTITY Tilde \' \'>'
          '<!ENTITY SucceedsEqual \' \'>'
          '<!ENTITY RightCeiling \' \'>'
          '<!ENTITY NotElement \' \'>'
          '<!ENTITY pound \' \'>'
          '<!ENTITY nacute \' \'>'
          '<!ENTITY curren \' \'>'
          '<!ENTITY Otilde \' \'>'
          '<!ENTITY Sqrt \' \'>'
          '<!ENTITY female \' \'>'
          '<!ENTITY Atilde \' \'>'
          '<!ENTITY check \' \'>'
          '<!ENTITY Jcirc \' \'>'
          '<!ENTITY Gcirc \' \'>'
          '<!ENTITY racute \' \'>'
          '<!ENTITY Aacute \' \'>'
          '<!ENTITY cent \' \'>'
          '<!ENTITY Eacute \' \'>'
          '<!ENTITY gcirc \' \'>'
          '<!ENTITY gacute \' \'>'
          '<!ENTITY Cap \' \'>'
          '<!ENTITY odot \' \'>'
          '<!ENTITY CircleTimes \' \'>'
          '<!ENTITY ogr \' \'>'
          '<!ENTITY ContourIntegral \' \'>'
          '<!ENTITY rect \' \'>'
          '<!ENTITY vartheta \' \'>'
          '<!ENTITY Ovalhollow \' \'>'
          '<!ENTITY shy \' \'>'
          '<!ENTITY Succeeds \' \'>'
          '<!ENTITY diamondsuit \' \'>'
          '<!ENTITY Brketopenst \' \'>'
          '<!ENTITY Precedes \' \'>'
          '<!ENTITY Ugr \' \'>'
          '<!ENTITY male \' \'>'
          '<!ENTITY Brketclosest \' \'>'
          '<!ENTITY IndentingNewLine \' \'>'
          '<!ENTITY Ycirc \' \'>'
          '<!ENTITY GreaterGreater \' \'>'
          '<!ENTITY frac56 \' \'>'
          '<!ENTITY LeftArrow \' \'>'
          '<!ENTITY Cross \' \'>'
          '<!ENTITY lsim \' \'>'
          '<!ENTITY UpArrow \' \'>'
          '<!ENTITY becaus \' \'>'
          '<!ENTITY permil \' \'>'
          '<!ENTITY Ccedil \' \'>'
          '<!ENTITY ReverseElement \' \'>'
          '<!ENTITY icirc \' \'>'
          '<!ENTITY Quadbond \' \'>'
          '<!ENTITY Pscr \' \'>'
          '<!ENTITY zeta \' \'>'
          '<!ENTITY itilde \' \'>'
          '<!ENTITY Yuml \' \'>'
          '<!ENTITY empty \' \'>'
          '<!ENTITY yacute \' \'>'
          '<!ENTITY jcirc \' \'>'
          '<!ENTITY Vee \' \'>'
          '<!ENTITY dtdot \' \'>'
          '<!ENTITY Lscr \'(Lscr)\'>'
          '<!ENTITY Egrave \'(Egrave)\'>'
          '<!ENTITY Mscr \'(Mscr)\'>'
          '<!ENTITY nlt \'(nlt)\'>'
          '<!ENTITY aleph \'(aleph)\'>'
          '<!ENTITY Cup \'(Cup)\'>'
          '<!ENTITY tfr \'(tfr)\'>'
          '<!ENTITY image \'(image)\'>'
          '<!ENTITY Utilde \'(Utilde)\'>'
          '<!ENTITY CloseCurlyQuote \'(CloseCurlyQuote)\'>'
          '<!ENTITY SmallCircle \'(SmallCircle)\'>'
          '<!ENTITY Itilde \'(Itilde)\'>'
          '<!ENTITY DoubleLongRightArrow \'(DoubleLongRightArrow)\'>'
          '<!ENTITY zacute \'(zacute)\'>'
          '<!ENTITY ugrave \'(ugrave)\'>'
          '<!ENTITY Therefore \'(Therefore)\'>'
          '<!ENTITY blank \'(blank)\'>'
          '<!ENTITY LeftRightArrow \'(LeftRightArrow)\'>'
          '<!ENTITY sharp \'(sharp)\'>'
          '<!ENTITY Hacek \'(Hacek)\'>'
          '<!ENTITY bigcirc \'(bigcirc)\'>'
          '<!ENTITY oelig \'(oelig)\'>'
          '<!ENTITY Lhalfcircle \'(Lhalfcircle)\'>'
          '<!ENTITY Euml \'(Euml)\'>'
          '<!ENTITY backprime \'(backprime)\'>'
          '<!ENTITY Iacute \'(Iacute)\'>'
          '<!ENTITY Uacute \'(Uacute)\'>'
          '<!ENTITY Cacute \'(Cacute)\'>'
          '<!ENTITY Dscr \'(Dscr)\'>'
          '<!ENTITY DoubleLeftArrow \'(DoubleLeftArrow)\'>'
          '<!ENTITY Fscr \'(Fscr)\'>'
          '<!ENTITY Not \'(Not)\'>'
          '<!ENTITY Upsilon \'(Upsilon)\'>'
          '<!ENTITY ndash \'(ndash)\'>'
          '<!ENTITY Xi \'(Xi)\'>'
          '<!ENTITY RightArrowLeftArrow \'(RightArrowLeftArrow)\'>'
          '<!ENTITY clubsuit \'(clubsuit)\'>'
          '<!ENTITY flat \'(flat)\'>'
          '<!ENTITY Rectsolid \'(Rectsolid)\'>'
          '<!ENTITY TripleDot \'(TripleDot)\'>'
          '<!ENTITY lacute \'(lacute)\'>'
          '<!ENTITY LongLeftRightArrow \'(LongLeftRightArrow)\'>'
          '<!ENTITY SubsetEqual \'(SubsetEqual)\'>'
          '<!ENTITY varrho \'(varrho)\'>'
          '<!ENTITY varsigma \'(varsigma)\'>'
          '<!ENTITY LeftArrowRightArrow \'(LeftArrowRightArrow)\'>'
          '<!ENTITY Because \'(Because)\'>'
          '<!ENTITY Ifr \'(Ifr)\'>'
          '<!ENTITY Rfr \'(Rfr)\'>'
          '<!ENTITY OverBrace \'(OverBrace)\'>'
          '<!ENTITY LongRightArrow \'(LongRightArrow)\'>'
          '<!ENTITY gsim \'(gsim)\'>'
          '<!ENTITY Jfr \'(Jfr)\'>'
          '<!ENTITY SuchThat \'(SuchThat)\'>'
          '<!ENTITY Wcirc \'(Wcirc)\'>'
          '<!ENTITY bigstar \'(bigstar)\'>'
          '<!ENTITY GreaterLess \'(GreaterLess)\'>'
          '<!ENTITY Oacute \'(Oacute)\'>'
          '<!ENTITY Hscr \'(Hscr)\'>'
          '<!ENTITY Aring \'(Aring)\'>'
          '<!ENTITY sacute \'(sacute)\'>'
          '<!ENTITY Nacute \'(Nacute)\'>'
          '<!ENTITY bullet \'(bullet)\'>'
          '<!ENTITY laquo \'(laquo)\'>'
          '<!ENTITY Ograve \'(Ograve)\'>'
          '<!ENTITY dArr \'(dArr)\'>'
          '<!ENTITY boxvr \'(boxvr)\'>'
          '<!ENTITY NotHumpEqual \'(NotHumpEqual)\'>'
          '<!ENTITY VerticalBar \'(VerticalBar)\'>'
          '<!ENTITY Igrave \'(Igrave)\'>'
          '<!ENTITY cir \'(cir)\'>'
          '<!ENTITY Rscr \'(Rscr)\'>'
          '<!ENTITY VerticalLine \'(VerticalLine)\'>'
          '<!ENTITY Wscr \'(Wscr)\'>'
          '<!ENTITY Agrave \'(Agrave)\'>'
          '<!ENTITY hearts \'(hearts)\'>'
          '<!ENTITY CircleMinus \'(CircleMinus)\'>'
          '<!ENTITY Xgr \'(Xgr)\'>'
          '<!ENTITY CapitalDifferentialD \'(CapitalDifferentialD)\'>'
          '<!ENTITY Yacute \'(Yacute)\'>'
          '<!ENTITY EqualTilde \'(EqualTilde)\'>'
          '<!ENTITY OverParenthesis \'(OverParenthesis)\'>'
          '<!ENTITY Uscr \'(Uscr)\'>'
          '<!ENTITY Copf \'(Copf)\'>'
          '<!ENTITY ShortRightArrow \'(ShortRightArrow)\'>'
          '<!ENTITY Proportion \'(Proportion)\'>'
          '<!ENTITY Ffr \'(Ffr)\'>'
          '<!ENTITY heartsuit \'(heartsuit)\'>'
          '<!ENTITY NotTildeEqual \'(NotTildeEqual)\'>'
          '<!ENTITY Escr \'(Escr)\'>'
          '<!ENTITY Nscr \'(Nscr)\'>'
          '<!ENTITY DownArrow \'(DownArrow)\'>'
          '<!ENTITY Square \'(Square)\'>'
          '<!ENTITY eth \'(eth)\'>'
          '<!ENTITY Centerline \'(Centerline)\'>'
          '<!ENTITY Tscr \'(Tscr)\'>'
          '<!ENTITY Iuml \'(Iuml)\'>'
          '<!ENTITY Jscr \'(Jscr)\'>'
          '<!ENTITY Equilibrium \'(Equilibrium)\'>'
          ']>\n')

