import importlib
helpers = importlib.import_module('.helpers', 'models')

######################################################################
#
######################################################################
table  = 'ca_tm_cancellation_proceedings'
body   =   ('(ST13ApplicationNumber BIGINT,'
            'proc_date STRING,'
            'LegalProceedingIdentifier STRING,'
            'ProceedingStageCode STRING,'
            'ProceedingStageDescriptionText_en STRING,'
            'ProceedingStageDescriptionText_fr STRING,'
            'LegalProceedingFilingDate STRING,'
            'OppositionCaseTypeDescription_en STRING,'
            'OppositionCaseTypeDescription_fr STRING,'
            'NationalStatusCategory STRING,'
            'NationalStatusCode STRING,'
            'NationalStatusDate STRING,'
            'NationalStatusInternalDescriptionText STRING,'
            'Plaintiff_LegalEntityName STRING,'
            'Plaintiff_EntityName STRING,'
            'Plaintiff_AddressLineText1 STRING,'
            'Plaintiff_AddressLineText2 STRING,'
            'Plaintiff_AddressLineText3 STRING,'
            'Plaintiff_GeographicRegionName STRING,'
            'Plaintiff_CountryCode STRING,'
            'Plaintiff_PostalCode STRING,'
            'Plaintiff_Cor_EntityName STRING,'
            'Plaintiff_Cor_AddressLineText1 STRING,'
            'Plaintiff_Cor_AddressLineText2 STRING,'
            'Plaintiff_Cor_AddressLineText3 STRING,'
            'Plaintiff_Cor_GeographicRegionName STRING,'
            'Plaintiff_Cor_CountryCode STRING,'
            'Plaintiff_Cor_PostalCode STRING,'
            'Plaintiff_Rep_CommentText STRING,'
            'Plaintiff_Rep_EntityName STRING,'
            'Plaintiff_Rep_AddressLineText1 STRING,'
            'Plaintiff_Rep_AddressLineText2 STRING,'
            'Plaintiff_Rep_AddressLineText3 STRING,'
            'Plaintiff_Rep_GeographicRegionName STRING,'
            'Plaintiff_Rep_CountryCode STRING,'
            'Plaintiff_Rep_PostalCode STRING,'
            'Defendant_EntityName STRING,'
            'Defendant_AddressLineText1 STRING,'
            'Defendant_AddressLineText2 STRING,'
            'Defendant_AddressLineText3 STRING,'
            'Defendant_GeographicRegionName STRING,'
            'Defendant_CountryCode STRING,'
            'Defendant_PostalCode STRING,'
            'Defendant_Cor_CommentText STRING,'
            'Defendant_Cor_EntityName STRING,'
            'Defendant_Cor_AddressLineText1 STRING,'
            'Defendant_Cor_AddressLineText2 STRING,'
            'Defendant_Cor_AddressLineText3 STRING,'
            'Defendant_Cor_GeographicRegionName STRING,'
            'Defendant_Cor_CountryCode STRING,'
            'Defendant_Cor_PostalCode STRING,'
            'Defendant_Rep_CommentText STRING,'
            'Defendant_Rep_EntityName STRING,'
            'Defendant_Rep_AddressLineText1 STRING,'
            'Defendant_Rep_AddressLineText2 STRING,'
            'Defendant_Rep_AddressLineText3 STRING,'
            'Defendant_Rep_GeographicRegionName STRING,'
            'Defendant_Rep_CountryCode STRING,'
            'Defendant_Rep_PostalCode STRING,'
            'PRIMARY KEY(ST13ApplicationNumber,proc_date,LegalProceedingIdentifier,ProceedingStageCode,ProceedingStageDescriptionText_en,ProceedingStageDescriptionText_fr)) STORED AS KUDU ')

body_ext = ('(ST13ApplicationNumber BIGINT,'
            'proc_date STRING,'
            'LegalProceedingIdentifier STRING,'
            'ProceedingStageCode STRING,'
            'ProceedingStageDescriptionText_en STRING,'
            'ProceedingStageDescriptionText_fr STRING,'
            'LegalProceedingFilingDate STRING,'
            'OppositionCaseTypeDescription_en STRING,'
            'OppositionCaseTypeDescription_fr STRING,'
            'NationalStatusCategry STRING,'
            'NationalStatusCode STRING,'
            'NationalStatusDate STRING,'
            'NationalStatusInternalDescriptionText STRING,'
            'Plaintiff_LegalEntityName STRING,'
            'Plaintiff_EntityName STRING,'
            'Plaintiff_AddressLineText1 STRING,'
            'Plaintiff_AddressLineText2 STRING,'
            'Plaintiff_AddressLineText3 STRING,'
            'Plaintiff_GeographicRegionName STRING,'
            'Plaintiff_CountryCode STRING,'
            'Plaintiff_PostalCode STRING,'
            'Plaintiff_Cor_EntityName STRING,'
            'Plaintiff_Cor_AddressLineText1 STRING,'
            'Plaintiff_Cor_AddressLineText2 STRING,'
            'Plaintiff_Cor_AddressLineText3 STRING,'
            'Plaintiff_Cor_GeographicRegionName STRING,'
            'Plaintiff_Cor_CountryCode STRING,'
            'Plaintiff_Cor_PostalCode STRING,'
            'Plaintiff_Rep_CommentText STRING,'
            'Plaintiff_Rep_EntityName STRING,'
            'Plaintiff_Rep_AddressLineText1 STRING,'
            'Plaintiff_Rep_AddressLineText2 STRING,'
            'Plaintiff_Rep_AddressLineText3 STRING,'
            'Plaintiff_Rep_GeographicRegionName STRING,'
            'Plaintiff_Rep_CountryCode STRING,'
            'Plaintiff_Rep_PostalCode STRING,'
            'Defendant_EntityName STRING,'
            'Defendant_AddressLineText1 STRING,'
            'Defendant_AddressLineText2 STRING,'
            'Defendant_AddressLineText3 STRING,'
            'Defendant_GeographicRegionName STRING,'
            'Defendant_CountryCode STRING,'
            'Defendant_PostalCode STRING,'
            'Defendant_Cor_CommentText STRING,'
            'Defendant_Cor_EntityName STRING,'
            'Defendant_Cor_AddressLineText1 STRING,'
            'Defendant_Cor_AddressLineText2 STRING,'
            'Defendant_Cor_AddressLineText3 STRING,'
            'Defendant_Cor_GeographicRegionName STRING,'
            'Defendant_Cor_CountryCode STRING,'
            'Defendant_Cor_PostalCode STRING,'
            'Defendant_Rep_CommentText STRING,'
            'Defendant_Rep_EntityName STRING,'
            'Defendant_Rep_AddressLineText1 STRING,'
            'Defendant_Rep_AddressLineText2 STRING,'
            'Defendant_Rep_AddressLineText3 STRING,'
            'Defendant_Rep_GeographicRegionName STRING,'
            'Defendant_Rep_CountryCode STRING,'
            'Defendant_Rep_PostalCode STRING)     ')

model = helpers.tbl_model(table, [body, body_ext])
